---
- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
    mode: 0775
    validate_certs: no

- name: Install EPEL
  yum: name=epel-release state=latest update_cache=yes

- name: Install Erlang
  yum: name=erlang update_cache=yes

- name: install rabbitmq-server
  yum: name=rabbitmq-server update_cache=yes
