version: "2"
defaults:
  username: rabbitmq
  user_group: rabbitmq
  vhost: my_vhost
  port: 5672

services:
  rabbitmq:
    image: centos:7
    ports:
      - 5672:{{ port }}
    environment:
      RABBITMQ_DEFAULT_USER: {{ username }}
      RABBITMQ_GROUP: {{ user_group }}
      RABBITMQ_DEFAULT_VHOST: {{ vhost }}
      RABBITMQ_NODE_PORT: {{ port }}
    command: ['/usr/bin/dumb-init','rabbitmq-server']
    dev_overrides:
      command: ['/usr/bin/dumb-init','rabbitmq-server']

registries: {}
